// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace emec.dbcontext.tables.Models;

public partial class eMecContext : DbContext
{
    public eMecContext(DbContextOptions<eMecContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TblHealthCheck> TblHealthChecks { get; set; }

    public virtual DbSet<TblRole> TblRoles { get; set; }

    public virtual DbSet<TblUser> TblUsers { get; set; }

    public virtual DbSet<TblUserRole> TblUserRoles { get; set; }

    public virtual DbSet<TblWsCustomer> TblWsCustomers { get; set; }

    public virtual DbSet<TblWsVehicle> TblWsVehicles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TblHealthCheck>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_HealthCheck");

            entity.ToTable("TBL_HealthCheck");

            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TblRole>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Roles__8AFACE1A6B41E23D");

            entity.ToTable("TBL_Roles");

            entity.HasIndex(e => e.RoleName, "UQ__Roles__8A2B6160797B8678").IsUnique();

            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TblUser>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CC4C18823AC2");

            entity.ToTable("TBL_Users");

            entity.HasIndex(e => e.UserName, "UQ__Users__C9F284568372B8A2").IsUnique();

            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.RefreshToken)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.RefreshTokenExpiry).HasColumnType("datetime");
            entity.Property(e => e.Salt)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<TblUserRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_UserRoles");

            entity.ToTable("TBL_UserRoles");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<TblWsCustomer>(entity =>
        {
            entity.ToTable("TBL_WS_Customer");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Address)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Fname)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("FName");
            entity.Property(e => e.Lname)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("LName");
            entity.Property(e => e.Nic)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("NIC");
            entity.Property(e => e.Phone1)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.Phone2)
                .HasMaxLength(15)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TblWsVehicle>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.Province, e.Prefix, e.Number });

            entity.ToTable("TBL_WS_Vehicle");

            entity.Property(e => e.Province)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.Prefix)
                .HasMaxLength(3)
                .IsFixedLength();
            entity.Property(e => e.Number)
                .HasMaxLength(4)
                .IsFixedLength();
            entity.Property(e => e.Brand)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.DeletedAt).HasColumnType("datetime");
            entity.Property(e => e.Model)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Remarks)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.Version)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Customer).WithMany(p => p.TblWsVehicles)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TBL_WS_Vehicle_TBL_WS_Customer");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}