// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace emec.dbcontext.tables.Models;

public partial class TblRole
{
    public int RoleId { get; set; }

    public string RoleName { get; set; }
}