// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace emec.dbcontext.tables.Models;

public partial class TblUser
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string PasswordHash { get; set; }

    public string Salt { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? RefreshTokenExpiry { get; set; }
}