// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace emec.dbcontext.tables.Models;

public partial class TblWsCustomer
{
    public Guid Id { get; set; }

    public string Fname { get; set; }

    public string Lname { get; set; }

    public string Address { get; set; }

    public string Nic { get; set; }

    public string Phone1 { get; set; }

    public string Phone2 { get; set; }

    public int Type { get; set; }

    public DateTime CreatedAt { get; set; }

    public int CreatedBy { get; set; }

    public bool Deleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual ICollection<TblWsVehicle> TblWsVehicles { get; set; } = new List<TblWsVehicle>();
}