// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace emec.dbcontext.tables.Models;

public partial class TblWsVehicle
{
    public Guid Id { get; set; }

    public string Province { get; set; }

    public string Prefix { get; set; }

    public string Number { get; set; }

    public string Brand { get; set; }

    public string Model { get; set; }

    public string Version { get; set; }

    public string YoM { get; set; }

    public string YoR { get; set; }

    public string Remarks { get; set; }

    public Guid CustomerId { get; set; }

    public DateTime CreatedAt { get; set; }

    public int CreatedBy { get; set; }

    public bool Deleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual TblWsCustomer Customer { get; set; }
}