//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emec.shared.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("emec.shared.Errors.ErrorResource", typeof(ErrorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Request.
        /// </summary>
        internal static string E0001 {
            get {
                return ResourceManager.GetString("E0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api action not permitted.
        /// </summary>
        internal static string E0002 {
            get {
                return ResourceManager.GetString("E0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired refresh token..
        /// </summary>
        internal static string E0003 {
            get {
                return ResourceManager.GetString("E0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request or attributes cannot be null..
        /// </summary>
        internal static string E0004 {
            get {
                return ResourceManager.GetString("E0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Id is required..
        /// </summary>
        internal static string E0005 {
            get {
                return ResourceManager.GetString("E0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province is required..
        /// </summary>
        internal static string E0006 {
            get {
                return ResourceManager.GetString("E0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix is required..
        /// </summary>
        internal static string E0007 {
            get {
                return ResourceManager.GetString("E0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number is required and must be non-zero..
        /// </summary>
        internal static string E0008 {
            get {
                return ResourceManager.GetString("E0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand is required..
        /// </summary>
        internal static string E0009 {
            get {
                return ResourceManager.GetString("E0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model is required..
        /// </summary>
        internal static string E0010 {
            get {
                return ResourceManager.GetString("E0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version is required..
        /// </summary>
        internal static string E0011 {
            get {
                return ResourceManager.GetString("E0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of Manufacture (YoM) is required and must be non-zero..
        /// </summary>
        internal static string E0012 {
            get {
                return ResourceManager.GetString("E0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of Registration (YoR) is required and must be non-zero..
        /// </summary>
        internal static string E0013 {
            get {
                return ResourceManager.GetString("E0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle number must have 4 digits.
        /// </summary>
        internal static string E0014 {
            get {
                return ResourceManager.GetString("E0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search keyword is required.
        /// </summary>
        internal static string E0015 {
            get {
                return ResourceManager.GetString("E0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request attributes are required.
        /// </summary>
        internal static string E0016 {
            get {
                return ResourceManager.GetString("E0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID is required.
        /// </summary>
        internal static string E0017 {
            get {
                return ResourceManager.GetString("E0017", resourceCulture);
            }
        }
    }
}
